### ISSUE TITLE
Delay state changes to debounce

### ISSUE THREAD

**Issue by elyscape** [apexskier/homebridge-eero-presence#2]
I've found that, if only one relevant device is connected to the network, if I move it around the apartment and it switches bands, the occupancy sensor will often flip to unoccupied for one cycle. It would be nice if there were an option that, when enabled, would delay the state change until multiple consecutive polls agreed with each other.

**Comment by apexskier** [comment]
I added a default 20 second timeout before marking unoccupied - I've noticed this as well. Thanks for the suggestion!

**Comment by apexskier** [comment]
Released in v1.2
